export const TRC20_TOKENS = [
  {
    id: '4tb-coin',
    symbol: '4tb',
    name: '4TB Coin',
    logo: 'https://cryptologos-data.vercel.app/assets/4tb-coin.png',
    contract: 'TQgcDvhr6c1EUDnFxiAmuYpBewT3uJSnHF',
    decimals: 4,
    price: 0,
    balance: 0,
  },
  {
    id: 'apenft',
    symbol: 'nft',
    name: 'APENFT',
    logo: 'https://cryptologos-data.vercel.app/assets/apenft.png',
    contract: 'TFczxzPhnThNSqr5by8tvxsdCFRRz6cPNq',
    decimals: 6,
    price: 0,
    balance: 0,
  },
  {
    id: 'astrazion',
    symbol: 'aznt',
    name: 'AstraZion',
    logo: 'https://cryptologos-data.vercel.app/assets/astrazion.png',
    contract: 'TD74cpU4JfMKhuWVs6uKYXKUy8nvC6EQ95',
    decimals: 6,
    price: 0,
    balance: 0,
  },
  {
    id: 'b1coin',
    symbol: 'bicoin',
    name: 'B1COIN',
    logo: 'https://cryptologos-data.vercel.app/assets/b1coin.png',
    contract: 'TF7ixydn7nfCgj9wQj3fRdKRAvsZ8egHcx',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'bemchain',
    symbol: 'bcn',
    name: 'Bemchain',
    logo: 'https://cryptologos-data.vercel.app/assets/bemchain.png',
    contract: 'TAoA331n3iKDkR62kAZ4H2n3vNL7y3d8x9',
    decimals: 6,
    price: 0,
    balance: 0,
  },
  {
    id: 'biaoqing-tron',
    symbol: 'biao',
    name: 'Biaoqing TRON',
    logo: 'https://cryptologos-data.vercel.app/assets/biaoqing-tron.jpg',
    contract: 'TR95WcjR78Y4puyv8BkbFuxaf4WcvmmPpd',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'bitcoin-trc20',
    symbol: 'btct',
    name: 'Bitcoin TRC20',
    logo: 'https://cryptologos-data.vercel.app/assets/bitcoin-trc20.png',
    contract: 'TN3W4H6rK2ce4vX9YnFQHwKENnHjoxb3m9',
    decimals: 8,
    price: 0,
    balance: 0,
  },
  {
    id: 'bittorrent',
    symbol: 'btt',
    name: 'BitTorrent',
    logo: 'https://cryptologos-data.vercel.app/assets/bittorrent.png',
    contract: 'TAFjULxiVgT4qWk6UZwjqwZXTSaGaqnVp4',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'black-phoenix',
    symbol: 'bpx',
    name: 'Black Phoenix',
    logo: 'https://cryptologos-data.vercel.app/assets/black-phoenix.jpg',
    contract: 'TXBcx59eDVndV5upFQnTR2xdvqFd5reXET',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'blake',
    symbol: 'blake',
    name: 'BLAKE',
    logo: 'https://cryptologos-data.vercel.app/assets/blake.jpg',
    contract: 'TXtu3Ke9mJQtPtAQxmoTbzu3N4Qx4XP9Y2',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'bms-coin',
    symbol: 'bms',
    name: 'BMS Coin',
    logo: 'https://cryptologos-data.vercel.app/assets/bms-coin.png',
    contract: 'TYQ2rbuRmcPuTQVWnx71BMsqxj46rteweH',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'brihlo',
    symbol: 'bril',
    name: 'BRIHLO',
    logo: 'https://cryptologos-data.vercel.app/assets/brihlo.png',
    contract: 'THkzgVF6wE9wUacsetbokJUophZtaLHRLJ',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'caprisun',
    symbol: 'csun',
    name: 'Caprisun',
    logo: 'https://cryptologos-data.vercel.app/assets/caprisun.jpg',
    contract: 'TKmrM2UUNcTsC5UjiujDHwzRAmzzTJDcYd',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'cashbackpro',
    symbol: 'cbp',
    name: 'CashBackPro',
    logo: 'https://cryptologos-data.vercel.app/assets/cashbackpro.png',
    contract: 'TL7RJPC7zqpj9B2F4RRc4mk4YpzuVrd4Ar',
    decimals: 6,
    price: 0,
    balance: 0,
  },
  {
    id: 'clecoin',
    symbol: 'cle',
    name: 'CLECOIN',
    logo: 'https://cryptologos-data.vercel.app/assets/clecoin.jpg',
    contract: 'TRPzBzxBBewcQkN5P687pDw24F1FPFqVtt',
    decimals: 6,
    price: 0,
    balance: 0,
  },
  {
    id: 'coconut-chicken',
    symbol: '$ccc',
    name: 'Coconut Chicken',
    logo: 'https://cryptologos-data.vercel.app/assets/coconut-chicken.png',
    contract: 'TRv9ipj4kKAZqQggQ7ceJpe5ERD1ZShpgs',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'companion-pet-coin',
    symbol: 'cpc',
    name: 'Companion Pet Coin',
    logo: 'https://cryptologos-data.vercel.app/assets/companion-pet-coin.jpg',
    contract: 'TKTtVPdJDKpEqEf8ny8p2BcSyUjGhoUeJN',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'core',
    symbol: 'cmcx',
    name: 'CORE MultiChain',
    logo: 'https://cryptologos-data.vercel.app/assets/core.png',
    contract: 'TKg1nGjtWYDcf1HNTSNQtwGwNAuTxd1X2A',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'cornatto',
    symbol: 'cnc',
    name: 'Cornatto',
    logo: 'https://cryptologos-data.vercel.app/assets/cornatto.png',
    contract: 'TL5BvThAMg9QBCvbgXu7HwHh8HqGdAq4DD',
    decimals: 10,
    price: 0,
    balance: 0,
  },
  {
    id: 'crosswallet',
    symbol: 'cwt',
    name: 'CrossWallet',
    logo: 'https://cryptologos-data.vercel.app/assets/crosswallet.png',
    contract: 'TY2Ge1YYphoAatwaBxa1zYfJVa8CqNyL6B',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'crypto-kit',
    symbol: 'kit',
    name: 'Crypto KIT',
    logo: 'https://cryptologos-data.vercel.app/assets/crypto-kit.jpg',
    contract: 'TQVkTUQPKWdr2JtTy9X8ZxYUMuwBQap3Y7',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'crypto-whale',
    symbol: 'whale',
    name: 'Crypto Whale',
    logo: 'https://cryptologos-data.vercel.app/assets/crypto-whale.png',
    contract: 'TWP6GgtstiuYbpygSFcZLzJQrj9eDVQcq2',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'cyber-dog',
    symbol: 'cdog',
    name: 'Cyber Dog',
    logo: 'https://cryptologos-data.vercel.app/assets/cyber-dog.jpeg',
    contract: 'TVXmroHbJsJ6rVm3wGn2G9723yz3Kbqp9x',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'cyberfm',
    symbol: 'cyfm',
    name: 'CyberFM',
    logo: 'https://cryptologos-data.vercel.app/assets/cyberfm.png',
    contract: 'TZ5jA9F5zGRgi9qk9ATMu6D7wyEpnxQGJh',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'degree-crypto-token',
    symbol: 'dct',
    name: 'Degree Crypto',
    logo: 'https://cryptologos-data.vercel.app/assets/degree-crypto-token.png',
    contract: 'TRwptGFfX3fuffAMbWDDLJZAZFmP6bGfqL',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'dragon-sun',
    symbol: 'drgn',
    name: 'Dragon Sun',
    logo: 'https://cryptologos-data.vercel.app/assets/dragon-sun.png',
    contract: 'TV5yB8f4AdoAfVVUdkytyZnX5e7SeGAZr2',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'fimarkcoin-com',
    symbol: 'fmc',
    name: 'Fimarkcoin.com',
    logo: 'https://cryptologos-data.vercel.app/assets/fimarkcoin-com.png',
    contract: 'TF8EjxT89LmcUNKV3fq55oeD5V44V7tjo2',
    decimals: 8,
    price: 0,
    balance: 0,
  },
  {
    id: 'finxflo',
    symbol: 'fxf',
    name: 'FINXFLO',
    logo: 'https://cryptologos-data.vercel.app/assets/finxflo.png',
    contract: 'TSNr126nQ8HKfXREqrqkBnxoQNHS5qJLg5',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'fofar-2',
    symbol: 'fofar',
    name: 'FoFar',
    logo: 'https://cryptologos-data.vercel.app/assets/fofar-2.jpg',
    contract: 'TUFonyWZ4Tza5MzgDj6g2u5rfdGoRVYG7g',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'ftx-users-debt',
    symbol: 'fud',
    name: "FTX Users' Debt",
    logo: 'https://cryptologos-data.vercel.app/assets/ftx-users-debt.jpg',
    contract: 'TQWQTZ7LzyttfnHQyfLUkKUs8eZZepgXiQ',
    decimals: 6,
    price: 0,
    balance: 0,
  },
  {
    id: 'global-commercial-business',
    symbol: 'gcb',
    name: 'Global Commercial Business',
    logo: 'https://cryptologos-data.vercel.app/assets/global-commercial-business.png',
    contract: 'TPN3AXU6GH9abi7xKchewq4jTuSFLGjq5i',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'golcoin',
    symbol: 'golc',
    name: 'GOLCOIN',
    logo: 'https://cryptologos-data.vercel.app/assets/golcoin.png',
    contract: 'TDXyBerEqKHrGLEQFH9S3prXHPQiqaDsTA',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'guarantee',
    symbol: 'tee',
    name: 'Guarantee',
    logo: 'https://cryptologos-data.vercel.app/assets/guarantee.png',
    contract: 'TQX4NJaSspcjXWUDHMgjcejRZ7k1VojNLz',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'hammy',
    symbol: 'hammy',
    name: 'HAMMY',
    logo: 'https://cryptologos-data.vercel.app/assets/hammy.png',
    contract: 'TEBdrpWiPVSU3cmR96wCVYgsxb9fwwJSZi',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'htx-dao',
    symbol: 'htx',
    name: 'HTX DAO',
    logo: 'https://cryptologos-data.vercel.app/assets/htx-dao.png',
    contract: 'TUPM7K8REVzD2UdV4R5fe5M8XbnR2DdoJ6',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'invest-zone',
    symbol: 'ivfun',
    name: 'Invest Zone',
    logo: 'https://cryptologos-data.vercel.app/assets/invest-zone.png',
    contract: 'TSig7sWzEL2K83mkJMQtbyPpiVSbR6pZnb',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'just',
    symbol: 'jst',
    name: 'JUST',
    logo: 'https://cryptologos-data.vercel.app/assets/just.png',
    contract: 'TCFLL5dx5ZJdKnWuesXxi1VPwjLVmWZZy9',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'justmoney-2',
    symbol: 'jm',
    name: 'JustMoney',
    logo: 'https://cryptologos-data.vercel.app/assets/justmoney-2.png',
    contract: 'TVHH59uHVpHzLDMFFpUgCx2dNAQqCzPhcR',
    decimals: 8,
    price: 0,
    balance: 0,
  },
  {
    id: 'just-stablecoin',
    symbol: 'usdj',
    name: 'JUST Stablecoin',
    logo: 'https://cryptologos-data.vercel.app/assets/just-stablecoin.png',
    contract: 'TMwFHYXLJaRUPeW6421aqXL4ZEzPRFGkGT',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'knight',
    symbol: 'knight',
    name: 'Darkness',
    logo: 'https://cryptologos-data.vercel.app/assets/knight.png',
    contract: 'THvqUNvSRvV1DRJ9wuugBVKeq3rFxpxJej',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'kyrrex',
    symbol: 'krrx',
    name: 'Kyrrex',
    logo: 'https://cryptologos-data.vercel.app/assets/kyrrex.jpg',
    contract: 'THS2ZuQowumzFPD1z3wchB1PijWMggUgmA',
    decimals: 4,
    price: 0,
    balance: 0,
  },
  {
    id: 'lumi-credits',
    symbol: 'lumi',
    name: 'LUMI Credits',
    logo: 'https://cryptologos-data.vercel.app/assets/lumi-credits.png',
    contract: 'TDBNKiYQ8yfJtT5MDP3byu7f1npJuG2DBN',
    decimals: 6,
    price: 0,
    balance: 0,
  },
  {
    id: 'madhouse',
    symbol: 'mad',
    name: 'Madhouse',
    logo: 'https://cryptologos-data.vercel.app/assets/madhouse.png',
    contract: 'TBoupmmqSwULKpa3jQJZuWNPDpbzfT2Grh',
    decimals: 6,
    price: 0,
    balance: 0,
  },
  {
    id: 'meow-2',
    symbol: 'meow',
    name: 'Meow',
    logo: 'https://cryptologos-data.vercel.app/assets/meow-2.png',
    contract: 'TR1iXU8Sp7oUYHXWiddsBervJzSbdibMFZ',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'mew-woof-dao',
    symbol: 'mwd',
    name: 'MEW WOOF DAO',
    logo: 'https://cryptologos-data.vercel.app/assets/mew-woof-dao.png',
    contract: 'TEfg1LnM3yApCjAgax35wDg6SRpmZFuQS3',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'muncat',
    symbol: 'muncat',
    name: 'MUNCAT',
    logo: 'https://cryptologos-data.vercel.app/assets/muncat.png',
    contract: 'TE2T2vLnEQT1XW647EAQAHWqd6NZL1hweR',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'mynth',
    symbol: 'mnt',
    name: 'Mynth',
    logo: 'https://cryptologos-data.vercel.app/assets/mynth.png',
    contract: 'TNzfB1nvRPusCn5UhQLxUbZaX7DFuWkxR4',
    decimals: 6,
    price: 0,
    balance: 0,
  },
  {
    id: 'neiro-on-tron',
    symbol: 'neiro',
    name: 'Neiro on Tron',
    logo: 'https://cryptologos-data.vercel.app/assets/neiro-on-tron.png',
    contract: 'TCGPc27oyS2x7S5pex7ssyZxZ2edPWonk2',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'nort',
    symbol: 'xrt',
    name: 'norT',
    logo: 'https://cryptologos-data.vercel.app/assets/nort.jpeg',
    contract: 'TLMgXeSPVQsBXQjUf6QXn575h8SEK782oV',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'osk',
    symbol: 'osk',
    name: 'OSK',
    logo: 'https://cryptologos-data.vercel.app/assets/osk.jpg',
    contract: 'TDk91SWz2GvwfZwMTGX21d4ngUUH8YZZAv',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'pallapay',
    symbol: 'palla',
    name: 'Pallapay',
    logo: 'https://cryptologos-data.vercel.app/assets/pallapay.png',
    contract: 'TCfLxS9xHxH8auBL3T8pf3NFTZhsxy4Ncg',
    decimals: 8,
    price: 0,
    balance: 0,
  },
  {
    id: 'pandafi',
    symbol: 'pfi',
    name: 'PandaFi',
    logo: 'https://cryptologos-data.vercel.app/assets/pandafi.png',
    contract: 'TJ9mxWPmQSJswqMakEehFWcAntg73odiAq',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'paynet-coin',
    symbol: 'payn',
    name: 'PAYNET',
    logo: 'https://cryptologos-data.vercel.app/assets/paynet-coin.jpg',
    contract: 'TQYuR8FpmhMJK3ZpfoTgERjaZRywqMnFAH',
    decimals: 8,
    price: 0,
    balance: 0,
  },
  {
    id: 'pearl-finance',
    symbol: 'pearl',
    name: 'Pearl Finance',
    logo: 'https://cryptologos-data.vercel.app/assets/pearl-finance.png',
    contract: 'TGbu32VEGpS4kDmjrmn5ZZJgUyHQiaweoq',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'pino-trx',
    symbol: 'pino',
    name: 'Pino TRX',
    logo: 'https://cryptologos-data.vercel.app/assets/pino-trx.jpeg',
    contract: 'TAbkLGngV1k8bNb5hnqW7oX46FG4Dbs5e2',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'prcy-coin',
    symbol: 'prcy',
    name: 'PRivaCY Coin',
    logo: 'https://cryptologos-data.vercel.app/assets/prcy-coin.png',
    contract: 'TYV5eu6UgSPtxVLkPD9YfxmUEcXhum35yS',
    decimals: 8,
    price: 0,
    balance: 0,
  },
  {
    id: 'proof-of-liquidity',
    symbol: 'pol',
    name: 'Proof Of Liquidity',
    logo: 'https://cryptologos-data.vercel.app/assets/proof-of-liquidity.png',
    contract: 'TWcDDx1Q6QEoBrJi9qehtZnD4vcXXuVLer',
    decimals: 8,
    price: 0,
    balance: 0,
  },
  {
    id: 'puss',
    symbol: 'puss',
    name: 'Puss',
    logo: 'https://cryptologos-data.vercel.app/assets/puss.jpg',
    contract: 'TX5eXdf8458bZ77fk8xdvUgiQmC3L93iv7',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'reallink',
    symbol: 'real',
    name: 'RealLink',
    logo: 'https://cryptologos-data.vercel.app/assets/reallink.jpg',
    contract: 'TGBfBt6Y2Dm3RHdNpZAdqywBsvfdysf834',
    decimals: 6,
    price: 0,
    balance: 0,
  },
  {
    id: 'revain',
    symbol: 'rev',
    name: 'Revain',
    logo: 'https://cryptologos-data.vercel.app/assets/revain.png',
    contract: 'TD4bVgcwj3FRbmAo283HxNvqZvY7T3uD8k',
    decimals: 6,
    price: 0,
    balance: 0,
  },
  {
    id: 'rock-4',
    symbol: 'rock',
    name: 'ROCK',
    logo: 'https://cryptologos-data.vercel.app/assets/rock-4.png',
    contract: 'TJvwMR3RjHc8jA9QwwjWGANrR3Y4scLSZm',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'rock-dao',
    symbol: 'rock',
    name: 'ROCK DAO',
    logo: 'https://cryptologos-data.vercel.app/assets/rock-dao.png',
    contract: 'TZ3c6bmoqVeq9YEEBMSNrBLq2rHJ1vR8Nc',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'satozhi',
    symbol: 'satoz',
    name: 'Satozhi',
    logo: 'https://cryptologos-data.vercel.app/assets/satozhi.jpg',
    contract: 'TYq22mVD6aQdvzYhNxVYtjmRBCQmmcp2EK',
    decimals: 8,
    price: 0,
    balance: 0,
  },
  {
    id: 's-d-o-g-e-on-tron',
    symbol: 'sdoge',
    name: 'S.D.O.G.E on Tron',
    logo: 'https://cryptologos-data.vercel.app/assets/s-d-o-g-e-on-tron.png',
    contract: 'TBGa9VN3w3t6YyD4fwgN8cuFSauoUVTHMN',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'socialswap-token',
    symbol: 'sst',
    name: 'Social Swap',
    logo: 'https://cryptologos-data.vercel.app/assets/socialswap-token.png',
    contract: 'TBLQs7LqUYAgzYirNtaiX3ixnCKnhrVVCe',
    decimals: 8,
    price: 0,
    balance: 0,
  },
  {
    id: 'squid-game',
    symbol: 'squid',
    name: 'Squid Game',
    logo: 'https://cryptologos-data.vercel.app/assets/squid-game.png',
    contract: 'TSjUeAj5y2p1QBX7353CKDAqHdb6gcpJhR',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'staked-trx',
    symbol: 'strx',
    name: 'Staked TRX',
    logo: 'https://cryptologos-data.vercel.app/assets/staked-trx.png',
    contract: 'TU3kjFuhtEo42tsCBtfYUAZxoqQ4yuSLQ5',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'staked-usdt',
    symbol: 'stusdt',
    name: 'Staked USDT',
    logo: 'https://cryptologos-data.vercel.app/assets/staked-usdt.jpg',
    contract: 'TThzxNRLrW2Brp9DcTQU8i4Wd9udCWEdZ3',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'sugar-boy',
    symbol: 'sugar',
    name: 'Sugar Boy',
    logo: 'https://cryptologos-data.vercel.app/assets/sugar-boy.png',
    contract: 'TQKQRxEDH2vhtxGB4obGeHwu7AqGDryU3C',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'sunbeans',
    symbol: 'beans',
    name: 'SUNBEANS',
    logo: 'https://cryptologos-data.vercel.app/assets/sunbeans.jpg',
    contract: 'TQCfza5xo7srwPsYvdpQgYbgQAUWcAcjSa',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'suncat',
    symbol: 'suncat',
    name: 'Suncat',
    logo: 'https://cryptologos-data.vercel.app/assets/suncat.jpeg',
    contract: 'TAwAg9wtQzTMFsijnSFotJrpxhMm3AqW1d',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'sundog',
    symbol: 'sundog',
    name: 'Sundog',
    logo: 'https://cryptologos-data.vercel.app/assets/sundog.png',
    contract: 'TXL6rJbvmjD46zeN1JssfgxvSo99qC8MRT',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'sunlion',
    symbol: 'sunlion',
    name: 'sunlion',
    logo: 'https://cryptologos-data.vercel.app/assets/sunlion.jpeg',
    contract: 'TBk4dXtfo6j3rxPc1VJDhA7BsVi2XHK1bi',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'sunned',
    symbol: 'sunned',
    name: 'SUNNED',
    logo: 'https://cryptologos-data.vercel.app/assets/sunned.png',
    contract: 'THMpAfhJwJic2V9SbReQhwXLPuRGSLsj5q',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'sunneiro',
    symbol: 'sunneiro',
    name: 'SunNeiro',
    logo: 'https://cryptologos-data.vercel.app/assets/sunneiro.png',
    contract: 'TNFsYemyso755pjPs19bfdEuDnchbDzqua',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'sunpepe',
    symbol: 'sunpepe',
    name: 'sunpepe',
    logo: 'https://cryptologos-data.vercel.app/assets/sunpepe.png',
    contract: 'TAzpJHxxgJd8f5AKjzndEndH3S9pzNUM5W',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'sunpig',
    symbol: 'sunpig',
    name: 'SUNPIG',
    logo: 'https://cryptologos-data.vercel.app/assets/sunpig.png',
    contract: 'TX4xgxs6ctAz8RFbpk4rPzBrULWHE7Siiq',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'sunpumptrading',
    symbol: 'spt',
    name: 'SunPumpTrading',
    logo: 'https://cryptologos-data.vercel.app/assets/sunpumptrading.jpg',
    contract: 'TN2tRjEMhgHSVKzj4ssy4gvHpXQNh5weSg',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'sun-token',
    symbol: 'sun',
    name: 'Sun Token',
    logo: 'https://cryptologos-data.vercel.app/assets/sun-token.png',
    contract: 'TSSMHYeV2uE9qYH95DqyoCuNCzEL1NvU3S',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'sun-tzu-2',
    symbol: 'tsu',
    name: 'Sun Tzu',
    logo: 'https://cryptologos-data.vercel.app/assets/sun-tzu-2.jpg',
    contract: 'TUPsKS6qYuLmY7q1Uuq5aCS4DwQcCCDmg3',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'sunwukong',
    symbol: 'sunwukong',
    name: 'SunWukong',
    logo: 'https://cryptologos-data.vercel.app/assets/sunwukong.jpeg',
    contract: 'TP3prcvQknVthrVnn281cKST56eWiLgJJM',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'swapz-app',
    symbol: 'swapz',
    name: 'SWAPZ.app',
    logo: 'https://cryptologos-data.vercel.app/assets/swapz-app.jpeg',
    contract: 'TKdpGm5wKPLz3stemW8gkGvAdhztJcDjcW',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'szn',
    symbol: 'szn',
    name: 'szn',
    logo: 'https://cryptologos-data.vercel.app/assets/szn.webp',
    contract: 'TDxL4V5LE6TYSFXSCWJkkSsCYbgmrDnTer',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'tether',
    symbol: 'usdt',
    name: 'Tether',
    logo: 'https://cryptologos-data.vercel.app/assets/tether.png',
    contract: 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t',
    decimals: 6,
    price: 0,
    balance: 0,
  },
  {
    id: 'topcat-2',
    symbol: 'topcat',
    name: 'Topcat',
    logo: 'https://cryptologos-data.vercel.app/assets/topcat-2.jpg',
    contract: 'TD6xZDStjpd5FjgpNGihSYnm46nQUA6Dsj',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'to-the-sun',
    symbol: 'sunpump',
    name: 'To The Sun',
    logo: 'https://cryptologos-data.vercel.app/assets/to-the-sun.png',
    contract: 'TMwk13CthNktLiNpo8WDRuUMpyrzZTVZYH',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'tourism-industry-metavers',
    symbol: 'tim',
    name: 'Tourism Industry Metavers',
    logo: 'https://cryptologos-data.vercel.app/assets/tourism-industry-metavers.png',
    contract: 'TQH4JFjzGnWswNeaCxFJi3pSqmsvTXULY8',
    decimals: 6,
    price: 0,
    balance: 0,
  },
  {
    id: 'trepe',
    symbol: '$trepe',
    name: 'Trepe',
    logo: 'https://cryptologos-data.vercel.app/assets/trepe.jpg',
    contract: 'THVR1Biz4ZYYxewha6Wmi47HeB5opj1dv2',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'tron-bull',
    symbol: 'bull',
    name: 'Tron Bull',
    logo: 'https://cryptologos-data.vercel.app/assets/tron-bull.png',
    contract: 'TAt4ufXFaHZAEV44ev7onThjTnF61SEaEM',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'tron-bull-coin',
    symbol: 'tbull',
    name: 'Tron Bull Coin',
    logo: 'https://cryptologos-data.vercel.app/assets/tron-bull-coin.png',
    contract: 'TPeoxx1VhUMnAUyjwWfximDYFDQaxNQQ45',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'tron-cat',
    symbol: 'tcat',
    name: 'Tron Cat',
    logo: 'https://cryptologos-data.vercel.app/assets/tron-cat.jpg',
    contract: 'TVgHqeP41s3qMDH3oKBsScEUzvyXw6bKAm',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'tronches',
    symbol: 'tronches',
    name: 'TRONCHES',
    logo: 'https://cryptologos-data.vercel.app/assets/tronches.jpg',
    contract: 'TVwzGbGPoQWXcN9CQ1q2REiMcMtV78MKPg',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'trondog',
    symbol: 'trondog',
    name: 'TronDog',
    logo: 'https://cryptologos-data.vercel.app/assets/trondog.png',
    contract: 'TEKWczHwjSiS75N37YSz1fgraZLuarks86',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'tronkey',
    symbol: 'tronkey',
    name: 'TRONKEY',
    logo: 'https://cryptologos-data.vercel.app/assets/tronkey.jpeg',
    contract: 'TRHsKfoPJxFHnJ4wJ8Zc9nmSNAyaNYqff7',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'tron-mascot',
    symbol: 'suntron',
    name: 'TRON MASCOT',
    logo: 'https://cryptologos-data.vercel.app/assets/tron-mascot.png',
    contract: 'TPP9Pq2LQwtrwfyUDLSyFsKJwJjFouf45B',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'true-usd',
    symbol: 'tusd',
    name: 'TrueUSD',
    logo: 'https://cryptologos-data.vercel.app/assets/true-usd.png',
    contract: 'TUpMhErZL2fhh4sVNULAbNKLokS4GjC1F4',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'ttcoin',
    symbol: 'tc',
    name: 'TTcoin',
    logo: 'https://cryptologos-data.vercel.app/assets/ttcoin.png',
    contract: 'TCMwzYUUCxLkTNpXjkYSBgXgqXwt7KJ82y',
    decimals: 4,
    price: 0,
    balance: 0,
  },
  {
    id: 'twiskers',
    symbol: 'twx',
    name: 'Twiskers',
    logo: 'https://cryptologos-data.vercel.app/assets/twiskers.png',
    contract: 'TTFreuJ4pYDaCeEMEtiR1GQDwPPrS4jKFk',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'uplift',
    symbol: 'lift',
    name: 'Uplift',
    logo: 'https://cryptologos-data.vercel.app/assets/uplift.png',
    contract: 'TGo8MJaSxvVVicZ1ixC7n3ibJMt9NJvxuU',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'upstabletoken',
    symbol: 'ustx',
    name: 'UpStable',
    logo: 'https://cryptologos-data.vercel.app/assets/upstabletoken.png',
    contract: 'TYX2iy3i3793YgKU5vqKxDnLpiBMSa5EdV',
    decimals: 6,
    price: 0,
    balance: 0,
  },
  {
    id: 'usd-coin',
    symbol: 'usdc',
    name: 'USDC',
    logo: 'https://cryptologos-data.vercel.app/assets/usd-coin.png',
    contract: 'TEkxiTehnzSmSe2XqrBj4w32RUN966rdz8',
    decimals: 6,
    price: 0,
    balance: 0,
  },
  {
    id: 'usdd',
    symbol: 'usdd',
    name: 'USDD',
    logo: 'https://cryptologos-data.vercel.app/assets/usdd.jpg',
    contract: 'TXDk8mbtRbXeYuMNS83CfKPaYYT8XWv9Hz',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'ushark',
    symbol: 'ushark',
    name: 'uShark Token',
    logo: 'https://cryptologos-data.vercel.app/assets/ushark.png',
    contract: 'TE9f8MGouEdh2jPqDaUgUVaJYLKkV6vhv6',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'vikita',
    symbol: 'vikita',
    name: 'VIKITA',
    logo: 'https://cryptologos-data.vercel.app/assets/vikita.jpg',
    contract: 'TP7r1pDoS1snMjEJE1kE17GRt3Df4mYuZz',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'weth',
    symbol: 'weth',
    name: 'WETH',
    logo: 'https://cryptologos-data.vercel.app/assets/weth.png',
    contract: 'THb4CqiFdwNHsWsQCs4JhzwjMWys4aqCbF',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'wfdp',
    symbol: 'wfdp',
    name: 'WFDP',
    logo: 'https://cryptologos-data.vercel.app/assets/wfdp.png',
    contract: 'TQb8rm1BDjArsBh78yw8enstQ3E85XFc9u',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'whitebit',
    symbol: 'wbt',
    name: 'WhiteBIT Coin',
    logo: 'https://cryptologos-data.vercel.app/assets/whitebit.png',
    contract: 'TFptbWaARrWTX5Yvy3gNG5Lm8BmhPx82Bt',
    decimals: 8,
    price: 0,
    balance: 0,
  },
  {
    id: 'wink',
    symbol: 'win',
    name: 'WINkLink',
    logo: 'https://cryptologos-data.vercel.app/assets/wink.png',
    contract: 'TLa2f6VPqDgRE67v1736s7bJ8Ray5wYjU7',
    decimals: 6,
    price: 0,
    balance: 0,
  },
  {
    id: 'wrapped-btt-tron',
    symbol: 'wbtt',
    name: 'Wrapped BTT (Tron)',
    logo: 'https://cryptologos-data.vercel.app/assets/wrapped-btt-tron.png',
    contract: 'TKfjV9RNKJJCqPvBtK8L7Knykh7DNWvnYt',
    decimals: 6,
    price: 0,
    balance: 0,
  },
  {
    id: 'wrapped-staked-usdt',
    symbol: 'wstusdt',
    name: 'Wrapped Staked USDT',
    logo: 'https://cryptologos-data.vercel.app/assets/wrapped-staked-usdt.jpeg',
    contract: 'TGkxzkDKyMeq2T7edKnyjZoFypyzjkkssq',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'wrapped-tron',
    symbol: 'wtrx',
    name: 'Wrapped Tron',
    logo: 'https://cryptologos-data.vercel.app/assets/wrapped-tron.jpg',
    contract: 'TNUC9Qb1rRpS5CbWLmNMxXBjyFoydXjWFR',
    decimals: 6,
    price: 0,
    balance: 0,
  },
  {
    id: 'xiao-lang-gou',
    symbol: 'xlg',
    name: 'xiao lang gou',
    logo: 'https://cryptologos-data.vercel.app/assets/xiao-lang-gou.jpg',
    contract: 'TQzUXP5eXHwrRMou9KYQQq7wEmu8KQF7mX',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'yalla-sun',
    symbol: 'ysu',
    name: 'Yalla Sun',
    logo: 'https://cryptologos-data.vercel.app/assets/yalla-sun.jpg',
    contract: 'TBAbgFHHpuLERRcUFvjnojtBjkBr39NFB7',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'yfx',
    symbol: 'yfx',
    name: 'Your Futures Exchange',
    logo: 'https://cryptologos-data.vercel.app/assets/yfx.png',
    contract: 'TAP7qf8Ao26ZAKYS5E6SGozUNoSLvBHsGa',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'zapo',
    symbol: 'zapo',
    name: 'ZAPO AI',
    logo: 'https://cryptologos-data.vercel.app/assets/zapo.jpeg',
    contract: 'TPUZseUsV89tM157aLfkuKYEaRKzBirmRb',
    decimals: 18,
    price: 0,
    balance: 0,
  },
  {
    id: 'zedxion',
    symbol: 'zedxion',
    name: 'Zedxion',
    logo: 'https://cryptologos-data.vercel.app/assets/zedxion.png',
    contract: 'TUP3g7kbaESRFRhULeA19USSrcVBEpWLVY',
    decimals: 18,
    price: 0,
    balance: 0,
  },
];

export const NILE_TESTNET_TOKENS = [
  {
    id: 'tether',
    symbol: 'usdt',
    name: 'Tether',
    logo: 'https://cryptologos-data.vercel.app/assets/tether.png',
    contract: 'TXYZopYRdj2D9XRtbG411XZZ3kM5VkAeBf',
    decimals: 6,
    price: 0,
    balance: 0,
  },
];

export const TRX_DATA = {
  id: 'tron',
  logo: 'https://static.tronscan.org/production/logo/trx.png',
  contract: '',
  name: 'TRON',
  symbol: 'trx',
  decimals: 6,
  balance: 0,
  price: 0,
  totalUSD: 0,
};
